### ISSUE TITLE
problem in HMMfwd 

### ISSUE THREAD

**Issue by naeimrezaeian** [alexsosn/MarslandMLAlgo#1]
hi , 
in your sample in observation array has 13 elements 

obs = np.array([3,1,1,3,0,3,3,3,1,1,0,2,2])

why in function HMMfwd  for started at index 0 to index 3 ? The rest of the elements do not need to calculate?

result : 
`('n=', 4)
('T=', 4)
('s=', 0, 'T=', 1, 'obs=', 1)
('s=', 1, 'T=', 1, 'obs=', 1)
('s=', 2, 'T=', 1, 'obs=', 1)
('s=', 3, 'T=', 1, 'obs=', 1)
*********
('s=', 0, 'T=', 2, 'obs=', 1)
('s=', 1, 'T=', 2, 'obs=', 1)
('s=', 2, 'T=', 2, 'obs=', 1)
('s=', 3, 'T=', 2, 'obs=', 1)
*********
('s=', 0, 'T=', 3, 'obs=', 3)
('s=', 1, 'T=', 3, 'obs=', 3)
('s=', 2, 'T=', 3, 'obs=', 3)
('s=', 3, 'T=', 3, 'obs=', 3)
*********
alpha :
[[ 0.025       0.          0.0005      0.0007728 ]
 [ 0.125       0.          0.00178     0.05329992]
 [ 0.075       0.          0.000255    0.00877293]
 [ 0.0875      0.          0.00025625  0.01164577]]

c=0.074491419
`
and second question 
in this sample what is **alpha,c**?

tnx

**Comment by alexsosn** [comment]
I'm not connected to [the author](http://stephenmonika.net/) of this code in any way. If you want something to be changed, or have any questions about the code, please, contact Stephen Marsland directly.
I uploaded this code to github for my own convenience, as on the author's site it's available only as a zip archive.
